// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCBSi7Sbg2lLCjBsaHBY8nfBi5hEohJUc',
    appId: '1:499447727835:android:9f7bb0dfa58f93ec3b6efe',
    messagingSenderId: '499447727835',
    projectId: 'mynotes-vidyt',
    storageBucket: 'mynotes-vidyt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEOJrYmiBVy5MPSuect-T64ieiMc_OYV8',
    appId: '1:499447727835:ios:ef3a5ab5b6c3f88d3b6efe',
    messagingSenderId: '499447727835',
    projectId: 'mynotes-vidyt',
    storageBucket: 'mynotes-vidyt.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBufbqq7nZf3vfNSER2xCG6ewdTmVneUI',
    appId: '1:499447727835:web:00a09596195bd4ea3b6efe',
    messagingSenderId: '499447727835',
    projectId: 'mynotes-vidyt',
    authDomain: 'mynotes-vidyt.firebaseapp.com',
    storageBucket: 'mynotes-vidyt.appspot.com',
    measurementId: 'G-63ERYBFP1S',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEOJrYmiBVy5MPSuect-T64ieiMc_OYV8',
    appId: '1:499447727835:ios:ef3a5ab5b6c3f88d3b6efe',
    messagingSenderId: '499447727835',
    projectId: 'mynotes-vidyt',
    storageBucket: 'mynotes-vidyt.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBufbqq7nZf3vfNSER2xCG6ewdTmVneUI',
    appId: '1:499447727835:web:7ecfe908cbff5bd53b6efe',
    messagingSenderId: '499447727835',
    projectId: 'mynotes-vidyt',
    authDomain: 'mynotes-vidyt.firebaseapp.com',
    storageBucket: 'mynotes-vidyt.appspot.com',
    measurementId: 'G-QL6XXQW6EP',
  );

}